version: 4.2
os: linux
files:
  - source: /slapp/Server/*
    destination: /xm/slapp/Server
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: xmslapp
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: xmslapp
  AfterInstall:
    - location: scripts/configure.sh
      timeout: 300
      runas: xmslapp
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 900
      runas: xmslapp
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: xmslapp
